### ISSUE TITLE
SDRAM Compatibility

### ISSUE THREAD

**Issue by blisstik** [MiSTer-devel/Arcade-Raizing_MiSTer#17]
The latest 0729 release of Garegga is unstable and freezes. I also notice that some parts around the ship flickers. I have a dual ram setup with the primary 128MB and secondary 32MB.

The other one's seem to play fine.

**Comment by psomashekar** [comment]
Please log all SDRAM related issues such as these here. Thanks. @atrac17

**Comment by psomashekar** [comment]
Please let me know if you have an IO board and fan too as overheating was also a symptom for some people.

**Comment by blisstik** [comment]
No IO board, no fan, in an open case with heatsink. The one's before 0729 worked just fine.

**Comment by psomashekar** [comment]
There's no difference in the SDRAM consumption between the builds by the way. Just minor bugs fixed. So if one build is working for you but another is not, it's not to do with SDRAM.

Secondly, the memory test checks something different than what we are looking for here, so it can be misleading. However, it can help to see if you have corrupt blocks, etc. The cores at the moment require a very high throughput from the SDRAM, so it depends on the module. It can be incompatible with some and cause errors.

**Comment by willoucom** [comment]
@atrac17 It worked the right way with the test version you provided.

**Comment by atrac17** [comment]
> @atrac17 It worked the right way with the test version you provided.

Great, do you see a lot of striping or GFX corruption?

@psomashekar and I will be both working on different changes in the future when time permits.

**Comment by psomashekar** [comment]
Yea we can try the best we can, but it's hard to really account for all the variations in SDRAM. Just to note, I have 128mb from mister Addons, the IO board and a fan.

**Comment by willoucom** [comment]
Hello again, I made some tests with batrider. 
There is a little bit of stripping on some explosions (often on the bosses) and with the shorty's bomb (the big laser). 
However I can't compare with the original since I don't own the pcb.

I have not seen any gfx corruption in my multiple attempts to complete the training mode.
To activate the single character mode, press Up, Up, Down, Down, Left, Right, Left, Right, B, A after inserting a coin on the title screen. Hope this helps to tests things with specific character.

@psomashekar  my Ram and IO board cames from ultimatemister

**Comment by blisstik** [comment]
I took out my 30mm fan once I went with dual SDRAM, now that it's summer, it's hot so I put it back again (I used USB for the fan pins). Seems to work fine now.

**Comment by atrac17** [comment]
> I took out my 30mm fan once I went with dual SDRAM, now that it's summer, it's hot so I put it back again (I used USB for the fan pins). Seems to work fine now.

Please don't close this as we are using it for everyone now not just you.

**Comment by psomashekar** [comment]
Reopened.

**Comment by alamone** [comment]
I have tried v2.5 and v2.9 128MB SDRAMs (single) on a MiSTer with analog I/O and USB board.  I get flickering when there are a lot of sprites onscreen.  I took a video:

[https://twitter.com/alamone/status/1558944518241603585](url)

**Comment by willoucom** [comment]
It seems that one of the recent updates broke the crc checksum at startup of some games, batrider for example.

**Comment by psomashekar** [comment]
> It seems that one of the recent updates broke the crc checksum at startup of some games, batrider for example.

Nothing was changed with SDRAM yet, so it's probably a coincidence. All that's been changed in the latest releases is graphics fixes for the gp9001.

@atrac17 is testing different clocking settings that might be more compatible with different memory modules.

**Comment by psomashekar** [comment]
latest build has fix for this.

**Comment by RGarciaLago** [comment]
I hope this is the right issue to post about this. I've been having problems with bypassing ram checks:

- For Garegga I consistently get "BAD" on ROM0.
- For Batrider I consistently get "BAD" on 68K ROM0 and 68K ROM2.
- For Grandprix / Sorcer Striker it seems to randomly work more often than not but I still get an error on occasion.
- Bakraid seems fine and clears the check on every mra, including the alternative ones.

Thanks for this awesome core! I'm running on v20221021. Please let me know if there's any other info I can provide.

**Comment by psomashekar** [comment]
> 

Unfortunately not much we can do about this as it is an sdram issue. Sorry about that.

**Comment by willoucom** [comment]
> I hope this is the right issue to post about this. I've been having problems with bypassing ram checks:

I may have a suggestion for you, can you try changing the fan voltage on your IO board to 5V instead of 3V. 
In my setup, I can run these games on 5V but not on 3V (I don't know why but I can live with that).

I hope this helps.

**Comment by RGarciaLago** [comment]
> > I hope this is the right issue to post about this. I've been having problems with bypassing ram checks:
> 
> 
> 
> I may have a suggestion for you, can you try changing the fan voltage on your IO board to 5V instead of 3V. 
> 
> In my setup, I can run these games on 5V but not on 3V (I don't know why but I can live with that).
> 
> 
> 
> I hope this helps.

Thanks for the suggestion! I tried searching but I couldn't find a guide on how to change fan voltage. Do you mind directing me to one?

**Comment by willoucom** [comment]
> > I may have a suggestion for you, can you try changing the fan voltage on your IO board to 5V instead of 3V.
> 
> Thanks for the suggestion! I tried searching but I couldn't find a guide on how to change fan voltage. Do you mind directing me to one?

Assuming your IO board is from a reputable vendor, you can find the jumper between the fan and the fan connector.

**Comment by RGarciaLago** [comment]
> > I took out my 30mm fan once I went with dual SDRAM, now that it's summer, it's hot so I put it back again (I used USB for the fan pins). Seems to work fine now.
> 
> Please don't close this as we are using it for everyone now not just you.

I'm sorry to use github comments in this way but can I chat with you real quick? I owe you an apology.

**Comment by x0rtrunks** [comment]
Still having this issue with a v2.9 ram board from Misteraddons. Is it just a lottery on whether your ram will work or not?

**Comment by svOOvzi** [comment]
I have the same issues with either getting `rom0 bad` or `rom error` in the raizing cores. I have v2.9 sdram from misteraddons as well. Though I have noticed that if the first game I load up shortly after turning on my mister is one of the raizing cores it will always load up and be playable, even if it normally only ever gets an error. I am able to play that core for hours with no errors or glitches as long as I do not turn the core off or restart it, otherwise the game will go back to the rom checking screen and return an error.

The following roms always work for me regardless if I have had the mister on for 30 seconds or 4 hours:
`Armed Police Batrider Special Ver. (USA) (Fri Feb 13 1998)`
`Battle Bakraid - Unlimited Version Special Ver. (USA) (Tue Jun 8 1999)`
`Battle Garegga (Zakk roms) (Europe USA Japan Asia) (Sat Feb 3 1996)`

No Sorcer Striker or Kingdom Grandprix roms work, unless it is the first core I load on the mister and do not turn it off/restart.

I am not sure what is different about the roms above compared to the other ones that all complain about errors, but the games are fully playable with no glitches that I can see. 

I hope this of help to everyone having these widespread issues @atrac17 @psomashekar
